services:
  angular-loki:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-loki
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - json-server
    networks:
      - loki-network

  json-server:
    build:
      context: ./json-server
    ports:
      - "3000:3000"
    volumes:
      - ./json-server/db.json:/app/db.json
    networks:
      - loki-network

networks:
  loki-network:
    driver: bridge
